# baseurl = "https://blog.session.it/open-developer-platform"
baseurl = "https://localhost:1313/open-developer-platform"

languageCode = "en-us"
title = "Open Developer Platform documentation"
theme = "material"
metadataformat = "yaml"
canonifyurls = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

# Generate HTML in the docs folder
publishDir = "docs"

[params]
	# General information
	author = "Symphony Software Foundation"
	description = "Open Developer Platform documentation."
	copyright = "Released under the Apache 2.0 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/maoo/open-developer-platform"

	# version = "0.9.0"
	logo = "/SymphonyFoundationSymbol.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "grey"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "symphonyOSS"
	github  = "symphonyoss"
	# email   = "infra@symphony.foundation"

[[menu.main]]
	name   = "Why ODP"
	url    = "why-odp/"
	weight = 20

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 30

[[menu.main]]
	name   = "Project infrastructure"
	url    = "project-infrastructure/"
	weight = 50

[[menu.main]]
	name   = "Continuous Integration"
	url    = "project-infrastructure/continuous-integration/"
	weight = 80

[[menu.main]]
	name   = "Documentation"
	url    = "project-infrastructure/documentation/"
	weight = 90

[[menu.main]]
	name   = "Languages"
	url    = "project-infrastructure/languages/"
	weight = 100

[[menu.main]]
	name   = "C#"
	url    = "project-infrastructure/languages/c-sharp/"
	weight = 120

[[menu.main]]
	name   = "Clojure"
	url    = "project-infrastructure/languages/clojure/"
	weight = 130

[[menu.main]]
	name   = "Java"
	url    = "project-infrastructure/languages/java/"
	weight = 140

[[menu.main]]
	name   = "Javascript"
	url    = "project-infrastructure/languages/javascript/"
	weight = 150

[[menu.main]]
	name   = "Python"
	url    = "project-infrastructure/languages/python/"
	weight = 160

[[menu.main]]
	name   = "Reporting"
	url    = "project-infrastructure/reporting/"
	weight = 110

[[menu.main]]
	name   = "BitHound"
	url    = "project-infrastructure/reporting/bithound/"
	weight = 170

[[menu.main]]
	name   = "CodeClimate"
	url    = "project-infrastructure/reporting/codeclimate/"
	weight = 180

[[menu.main]]
	name   = "Coverity Scan"
	url    = "project-infrastructure/reporting/coverityscan/"
	weight = 190

[[menu.main]]
	name   = "NodeSecurity"
	url    = "project-infrastructure/reporting/nodesecurity/"
	weight = 200

[[menu.main]]
	name   = "SonarCloud"
	url    = "project-infrastructure/reporting/sonarcloud/"
	weight = 210

[[menu.main]]
	name   = "VersionEye"
	url    = "project-infrastructure/reporting/versioneye/"
	weight = 220

[[menu.main]]
	name   = "Technologies"
	url    = "technologies/"
	weight = 60

[[menu.main]]
	name   = "Resources"
	url    = "resources/"
	weight = 70
